### ISSUE TITLE
Font setting has no effect

### ISSUE THREAD

**Issue by metamas** [ijgnd/anki__syntax-highlighting#2]
No matter which font I set in the plugin config (even default), I get the same serif font.
![image](https://user-images.githubusercontent.com/2520253/81463404-464b6e00-916e-11ea-85b0-69ef00ca4ac3.png)

I have verified the following:
- `_styles_for_syntax_highlighting.css` exists in Anki's `collection.media` directory
- `@import url("_styles_for_syntax_highlighting.css")` is at the top of each card's stylesheet
- the font setting changes the `font-family` rule in `_styles_for_syntax_highlighting.css`
- the font that I am choosing is installed on my system

**Comment by ijgnd** [comment]
Thanks for notifying me about this problem.

Could you test this version from [here](https://github.com/ijgnd/anki__syntax-highlighting/releases/download/2.95/anki__syntax-highlighting__2020-05-10.ankiaddon)? A guide for installing .ankiaddon files is [here](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation-macos.gif).

I have a code and pre tag inside the highlight tag and so the general code/pre settings seem to have been applied. So I added this to all class styling templates and now it works for me. 

```css
.highlight code {
    font-family: %s;
}

.highlight pre {
    font-family: %s;
}
```

Does this fix it for you? 

I made this add-on to learn about making pyqt guis and about html and css. So you probably know more about this than me. If you have any fixes, improvements or other bug reports for/about the code they would be very welcome ...

**Comment by metamas** [comment]
Hey, sorry for the delayed reply. I actually uninstalled the add-on, instead opting to maintain my own custom stylesheet — which doesn't require much complexity to meet my own needs. But I did get some inspiration/guidance from the one included in this add-on. So thank for that.
